### ISSUE TITLE
Right clicking animals (not chickens) with a Chicken Catcher crashes

### ISSUE THREAD

**Issue by toqueteos** [cnlimiter/MoreChickens#13]
Seems to be same error as #2

I'm using latest version `1.1.2.0` (from CurseForge).

```
[18Dec2021 17:58:33.558] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: com/sun/javafx/geom/Vec3d
        at cn.evolvefield.mods.morechickens.common.item.CatcherItem.func_111207_a(CatcherItem.java:55) ~[chickens:1.16.5-1.1.2.0]
        at net.minecraft.item.ItemStack.func_111282_a_(ItemStack.java:340) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:956) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1194) ~[?:?]
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?]
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.geom.Vec3d
        at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_292]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
        ... 20 more
```

**Comment by VulpesStella** [comment]
Attributed to a wrong import. Limiter himself is busy with work at this moment :(. If necessary, I'll fix it in my fork and offer a patched version :D

**Comment by VulpesStella** [comment]
Fixed in the latest 1.1.2.1 on Curseforge.
